Push pkgs.hello to attic
mlabs-haskell/cardano.nix pull request #12
Opened 2023-11-20 11:29 UTC by zmrocze

WIP and untested

2023-11-30 13:11 UTC, aciceri commented on shell/default.nix
> +        hci
I'm not sure if I want this here. It's going to be used only by us at the end of the day, it will increase the shell's closure size for nothing

2023-11-30 13:18 UTC, aciceri requested changes
Could you please refactor this PR into a PR to [hercules-ci/hercules-ci-effects]()?
Keep the PR a draft until I send you the function that, given a flake, returns the build closure of a flake. Otherwise perhaps I can directly add commits for it your PR if you create it from a branch on [our fork](mlabs-haskell/hercules-ci-effects/).

2024-01-05 14:36 UTC, zmrocze commented
failed lint

2024-01-30 23:50 UTC, brainrake commented
Failing because of a bug. https://github.com/hercules-ci/hercules-ci-effects/pull/165#pullrequestreview-1852593841

2024-02-15 15:42 UTC, aciceri approved these changes

2024-02-15 15:42 UTC, merged