Add license information and reuse linter
mlabs-haskell/cardano.nix pull request #15
Opened 2023-12-18 15:16 UTC by avnik

2023-12-18 18:51 UTC, aciceri commented
Please add the the license also to the docs page in the website.

2023-12-19 17:07 UTC, avnik commented
@aciceri fixed

2023-12-20 11:45 UTC, aciceri requested changes
Could you please rename commits following conventional commits as usual? (I also always forget and then have to rename, I'm starting to doubt how useful they really are in our case)

2023-12-20 11:45 UTC, aciceri commented on .reuse/dep5
> +Upstream-Contact: <https://github.com/mlabs-haskell/cardano.nix>
Please change contact to `legal@mlabs.city`

2023-12-20 11:45 UTC, aciceri commented on .reuse/dep5
> +Files: *.lock *.nix *.md
If I understood it correctly from [here](https://reuse.software/spec/) or you put a comment at the beginning of files or you use this file to specify multiple sources at the same time.
Personally I prefer the latter way.

I can't understand what it your reasoning behind doing a mix of both. For instance why the you manually added the string to the `yaml` file?

Also, does it make sense licensing lockfiles or `.gitignore`s?

2023-12-20 15:09 UTC, avnik commented on .reuse/dep5
> +Upstream-Contact: <https://github.com/mlabs-haskell/cardano.nix>
done

2023-12-20 15:10 UTC, avnik commented on .reuse/dep5
> +Files: *.lock *.nix *.md
I moved all to dep5, so all lint check passed, also add reuse tool to devshell

2023-12-20 17:07 UTC, aciceri approved these changes

2023-12-20 17:07 UTC, merged