Cardano-db-sync module
mlabs-haskell/cardano.nix pull request #59
Opened 2024-04-09 15:29 UTC by zmrocze

solves issue #58. 
WIP: need to fix test.

TODO:
 - update with http-proxy to expose postgres

2024-04-30 12:42 UTC, zmrocze commented
eh, attic input fails to build with these nixpkgs. but still id say go ahead and review

2024-04-30 15:30 UTC, zmrocze commented
our nixos tests run forever in CI. Locally it's maybe 25 secs for me. But previously the `db-sync` failed after reaching 100s timeout (which it reached after many minutes (?))

2024-05-02 10:34 UTC, aciceri reviewed
I cannot run the test locally using
```nix run .#apps.x86_64-linux.vmTests-cardano-db-sync```
I get the following error:
```
nix run .#apps.x86_64-linux.vmTests-cardano-db-sync
```
Check also #69 

Anyway the test seems good! :muscle: You said it works locally, right? Any idea why it doesn't work on CI? You increased the timeout and decreased the target percentage, both reasonable actions.

2024-05-02 10:34 UTC, aciceri commented on flake.nix
> +      url = "github:intersectmbo/cardano-db-sync?ref=13.2.0.1"; # compatible with 8.7.3
```suggestion
      url = "github:intersectmbo/cardano-db-sync/13.2.0.1"; # compatible with 8.7.3
```

You can also directly write this.

2024-05-02 18:16 UTC, brainrake requested changes

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +  cfg = config.cardano.cardano-db-sync;
`config.cardano.db-sync`

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    # `services.cardano-db-sync` module options:
don't copy the options, use them directly

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    _environment = mkOption {
this option is not needed, use the value directly

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +            assertion = config.cardano.node.enable;
not necessarily, if the node is running on another machine

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +            message = "When postgres is enabled, we use the ensureDBOwnership option which expects the user name to match db name.";
do we?

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +          authentication =
use ensureDBOwnership instead

2024-05-02 18:16 UTC, brainrake commented on modules/default.nix
> +    cardano-db-sync = {
`db-sync`

2024-05-02 18:16 UTC, brainrake commented on tests/cardano-db-sync.nix
> +  perSystem.vmTests.tests.cardano-db-sync = {
`db-sync`

2024-05-02 18:16 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    database = {
don't copy the options, use them directly

2024-05-02 20:06 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    # `services.cardano-db-sync` module options:
only add an option when it does more than just set the same option in the service, eg. setting multiple options or starting new services

2024-05-05 16:36 UTC, zmrocze commented on modules/cardano-db-sync.nix
> +            assertion = config.cardano.node.enable;
Okey, then I'll also add socketPath as an option, as now there is: 

```nix
          inherit (config.cardano.node) socketPath;
```

2024-05-05 17:42 UTC, zmrocze commented on modules/cardano-db-sync.nix
> +        default = "/run/postgresql";
went with:

```
# if postgres is enabled, use first socket from postgresql settings or default to /run/postgresql
if cfg.postgres.enable then builtins.head ((config.services.postgresql.settings.unix_socket_directories or []) ++ [ "/run/postgresql" ]);
```

2024-05-05 17:43 UTC, zmrocze commented on modules/cardano-db-sync.nix
> +    # `services.cardano-db-sync` module options:
wasnt sure about that myself, good

2024-05-05 18:00 UTC, zmrocze commented on modules/cardano-db-sync.nix
> +            message = "When postgres is enabled, we use the ensureDBOwnership option which expects the user name to match db name.";
```nix
          ensureUsers = [
            {
              name = "${cfg.database.name}";
              ensureDBOwnership = true;
            }
          ];
```

this means that `cfg.database.name` has access to `cfg.database.name` database, so if `database.name` is different, then the user needs to overwrite these permissions himself. 
But I should make it a warning I now think.

2024-05-05 18:03 UTC, zmrocze commented on modules/cardano-db-sync.nix
> +    database = {
for `port` and `socketDir` we set better defaults so we repeat these 2 options. Maybe it's better then to repeat all of `database.<...>` options? for intuitive consistency

2024-05-05 18:15 UTC, zmrocze commented on flake.nix
>      };
ill fix at root https://github.com/hercules-ci/hercules-ci-effects/pull/165 if nixpkgs there allow

2024-05-08 12:31 UTC, brainrake requested changes

2024-05-08 12:31 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    database = {
don't repeat the options, just set the defaults in the `cardano.db-sync` implementation

2024-05-08 12:31 UTC, brainrake commented on modules/cardano-db-sync.nix
> +    nodeSocketPath = mkOption {
we don't need this option, set  `services.cardano-db-sync.socketPath =  cardano.node.socketPath` in the implementation

2024-05-14 15:59 UTC, zmrocze commented
@brainrake i think it's fine now, would you check once more?
I simply removed the marked redundant options and the redundent postgres `authentication` setting (relic of some fix while experimenting). 

### Irrelevant note on the side:
Before I was under the impression that you're supposed to abstract away the underlying module (here `services.cardano-db-sync`) with your module (`cardano.db-sync`) - and make the user not touch the underlying module. I see it's differently with nixos modules, but it does make some sense, I mean it's more direct and doesn't repeat and in the end the module abstraction is always going to be leaky. On the downside the user needs to not only read the option docs but also the source including imports.

2024-05-16 21:01 UTC, brainrake commented on modules/cardano-db-sync.nix
> +            message = "When postgres is enabled, we use the ensureDBOwnership option which expects the user name to match db name.";
added assertion

2024-05-16 21:12 UTC, brainrake commented
Thanks @zmrocze , that makes sense. I think you solved one part by mentoning `services.cardano-db-sync` in the `cardano.db.sync.enable` documentation. We can make it more explicit, or add a link. Another part is rendering the documentation for the `services.*` modules: https://github.com/mlabs-haskell/cardano.nix/pull/71 .

Let me explain. There were upstream modules for cardano-node and cardano-db-sync. Wrapping everything leads to a large amount of extra code with no apparent advantage except having all the options in the same namespace. So we went the opposite way, not wrapping anything, just adding the minimum options to support default use cases (sometimes just `enable`), and setting options to coordinate between modules. You can set up the default use cases with the very few options under `cardano.*`. If you need more configurability, you can use the modules.
Another advantage is that modules under `services.*` without any dependencies by just importing the file. They can be easily contributed upstream or to nixpkgs.

2024-05-16 21:12 UTC, merged