WIP: blockfrost module and test
mlabs-haskell/cardano.nix pull request #81
Opened 2024-05-27 17:59 UTC by avnik

2024-05-31 14:30 UTC, aciceri reviewed
I prepared [a branch](https://github.com/mlabs-haskell/cardano.nix/pull/83) with minimal changes to make CI happy. Feel free to re-implement them here.

Also in the branch I'm also starting an ssh server so that you can connect with `ssh root@localhost -p 2000` after having started the test interactively with `nix run .#vmTests-blockfrost -- --interactive`.
I don't if you already knew this "trick" but I believe it can help a lot.

Moreover if possible let's test something more significative besides `/health`, perhaps we can check `/blocks/latest` to see if the slot number is greater than a certain amount? Something similar to what we did for `cardano-db-sync` I mean.

2024-05-31 14:30 UTC, aciceri commented on flake.nix
> +    };
We support multiple versions for the same packages now. Even if we'll have only one blockfrost for now I would already start preparing multiple blockfrost versions support for instance by renaming this input to something like `blockrost-2.0.2`. Feel free to address this in another PR so that we can merge this ASAP.

2024-05-31 14:30 UTC, aciceri commented on flake.nix
> +    };
Take a look at what has been done for `cardano-node`, `ogmios` and `kupo`. Also you should export the blockfrost derivation between this flake's packages.

2024-05-31 14:30 UTC, aciceri commented on tests/blockfrost.nix
> +        machine.succeed("curl http://localhost:3000/health")
I believe it's `/api/v0/health`

2024-05-31 14:30 UTC, aciceri commented on tests/blockfrost.nix
> +        time.sleep(10)
The reason why the test is failing is because this is not enough in CI. Anyway I would avoid using timeouts like this and suggest `machine.wait_until_succeeds()`.

2024-05-31 14:30 UTC, aciceri commented on tests/blockfrost.nix
> +        print(machine.succeed("systemd-analyze security blockfrost"))
For some reason this is also returning non-zero, I haven't investigated it.

2024-06-18 13:22 UTC, avnik commented on tests/blockfrost.nix
> +        print(machine.succeed("systemd-analyze security blockfrost"))
Different module name, it should be "blockfrost-ryo". Already fixed this

2024-06-18 13:24 UTC, avnik commented on tests/blockfrost.nix
> +        machine.succeed("curl http://localhost:3000/health")
Nope, `/api/v0` is only on public instances, local ones have straight `/health`

2024-06-25 13:51 UTC, aciceri reviewed
@brainrake could you also please take a look? Especially for what concerns the internal coherence with other modules and if the options interface really makes sense in all cases (what if one runs postgres on a different machine? These kind of scenarios I mean...). I was wondering if it should also have an assertion but I'm not sure what it should assert.

PS: @avnik remember to check how docs look like

2024-06-25 13:51 UTC, aciceri commented on flake.nix
> +    };
Ok let's ignore this until we support multiple versions.

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +        '';
Shouldn't we put something here?

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +          server.debug = true;
This is related to logs, right? Do we want it by default? Don't have a strong opinion honestly...

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +        '';
Check [here](https://github.com/mlabs-haskell/cardano.nix/blob/f641fb662d17d38a2d7ca543966d36f39c9a6cba/modules/db-sync.nix#L13). I t would be nice also having an example.

2024-06-25 13:51 UTC, aciceri commented on tests/blockfrost.nix
> +      nodes .machine = {pkgs, ...}: {
```suggestion
      nodes.machine = {pkgs, ...}: {
```

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +        #          MemoryDenyWriteExecute = true;
```suggestion
        # MemoryDenyWriteExecute = true;
```

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +        #          SystemCallFilter = ["@system-service" "~@privileged"];
```suggestion
        # SystemCallFilter = ["@system-service" "~@privileged"];
```

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +          users postgres postgres
Why is this line necessary?

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +          users postgres postgres
I saw that you probably took it from the upstream README

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +          users postgres postgres
What happens without it?

2024-06-25 13:51 UTC, aciceri commented on modules/blockfrost.nix
> +          local all all ident map=users
And what about this one instead?

2024-06-25 14:16 UTC, avnik commented on modules/blockfrost.nix
> +          users postgres postgres
Yes, is nessesary
```
machine # [  106.447725] postgres[3026]: [3026] LOG:  no match in usermap "users" for user "postgres" authenticated as "postgres"
machine # [  106.449903] postgres[3026]: [3026] FATAL:  Peer authentication failed for user "postgres"
```
(if it removed)

2024-06-25 14:16 UTC, avnik commented on modules/blockfrost.nix
> +          local all all ident map=users
This enable mapping mentioned above

2024-06-25 14:18 UTC, avnik commented on modules/blockfrost.nix
> +          server.debug = true;
Yes, debug probably could be removed.  Was need to figure out that we had db connection issues

2024-06-29 18:31 UTC, brainrake requested changes

2024-06-29 18:31 UTC, brainrake commented on modules/blockfrost.nix
> +  dbsync-cfg = config.services.cardano-db-sync;
```suggestion
  dbsync-cfg = config.services.cardano-db-sync or null;
```
we have to check the module exists

2024-06-29 18:31 UTC, brainrake commented on modules/blockfrost.nix
> +            inherit (dbsync-cfg.postgres) user port database;
```suggestion
            user = mkIf (dbsync-cfg.enabled or false) dbsync-cfg.postgres.user; 
            ...
```
we have to check if the module exists and is enabled

2024-06-29 18:31 UTC, brainrake commented on modules/blockfrost.nix
> +          users ${config.services.blockfrost.user} ${config.services.cardano-db-sync.postgres.user}
check that module exists and is enabled

2024-06-29 18:31 UTC, brainrake commented on modules/blockfrost.nix
> +        # FIXME: Turn MemoryDenyWriteExecute prevent service from work
remove this line then. we only have to disable what is not needed.

2024-06-29 18:31 UTC, brainrake commented on modules/blockfrost.nix
> +        # FIXME: Turn SystemCallFilter prevent service from work
chcek what filters work, add missing filters

2024-07-15 10:32 UTC, merged